### ISSUE TITLE
Add button for "Stream Mode"

### ISSUE THREAD

**Issue by groteworld** [harvestmoonspeedruns/hm64-bingo#1]
It would be great to add a button in the bottom corners to turn the page into "Stream Mode"

This would include:
* turning the background a solid color so that you can use it do chromakey transparency on
* remove seed input field and logo

**Comment by spenserg** [comment]
Stream mode added. Clicking the button at the bottom will remove the header and logo as well as the input box and button. Make sure the chart is set up properly first, because there's no way to go back to the previous mode; you'll have to refresh the page if you want the inputs back.
